server:
  port: 8080

spring:
  application:
    name: omc-leads-api

  devtools:
    add-properties: false

  profiles:
    include:

  datasource:
    url: jdbc:postgresql://localhost:5432/omc_leads_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
