server:
  port: 8080

spring:
  application:
    name: omc-leads-api

  devtools:
    add-properties: false

  profiles:
    include:

  datasource:
    url: jdbc:postgresql://localhost:5432/omc_leads_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: http://localhost:4200,http://localhost:8080
